name: ctrlfirl
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.3
  dart_openai: ^5.0.0
  dio: ^5.4.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.10
  flutter_tesseract_ocr: ^0.4.23
  google_ml_text_recognizer: ^0.0.3
  google_mlkit_text_recognition: ^0.8.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  provider: ^6.1.1
  skeletonizer: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
